# Generated by Django 4.0.1 on 2023-10-13 00:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_chat_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatMessage',
        ),
    ]
